
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "mark",
  "secret": "pass1238",

}

###

POST http://localhost:3001/signup
Content-Type: application/json

{
  "username": "ali",
  "secret": "pass1238",
  "email": "ali@gmail.com",
  "first_name": "Ali",
  "last_name": "Mora"
}
